import type {
  Announcement,
  Banner,
  FlashSale,
  HomepageSection,
  MarqueeItem,
  PromoPopup,
  RythuBatch,
  StorefrontData,
  Testimonial,
} from '@next360/types/cms'
import type { Category, Product } from '@next360/types/product'
import type { PlatformMode, Zone, ZoneModeConfig } from '@next360/types/location'

const categories: Category[] = [
  { id: 'grains', name: 'Grains', slug: 'grains', icon: '🌾', _count: { products: 2 } },
  { id: 'oils', name: 'Oils', slug: 'oils', icon: '🥥', _count: { products: 1 } },
  { id: 'spices', name: 'Spices', slug: 'spices', icon: '🌿', _count: { products: 1 } },
  { id: 'pulses', name: 'Pulses', slug: 'pulses', icon: '🫘', _count: { products: 1 } },
  { id: 'superfoods', name: 'Superfoods', slug: 'superfoods', icon: '🌱', _count: { products: 1 } },
  { id: 'dairy', name: 'Dairy', slug: 'dairy', icon: '🧈', _count: { products: 1 } },
  { id: 'sweeteners', name: 'Sweeteners', slug: 'sweeteners', icon: '🍯', _count: { products: 1 } },
]

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Organic Basmati Rice',
    slug: 'organic-basmati-rice',
    description: 'Aromatic long-grain basmati rice grown in the fertile soils of Warangal using 100% organic methods.',
    shortDesc: 'Fragrant, aged organic basmati rice.',
    price: 18000,
    originalPrice: 24000,
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=900&auto=format&fit=crop'],
    categoryId: 'grains',
    category: categories[0],
    region: 'Warangal',
    weight: ['1 kg', '5 kg'],
    certifications: ['NPOP'],
    tags: ['Bestseller', 'Aromatic'],
    healthGoalTags: ['energy', 'digestion'],
    seasonalMonths: [10, 11, 12, 1, 2],
    nutritionFacts: { servingSize: '100g', calories: 160, protein: '2g', carbs: '9g', fat: '15g', fiber: '7g', sugar: '1g', sodium: '7mg' },
    isFeatured: true,
    isOrganic: true,
    inStock: true,
    stock: 500,
    lowStockThresh: 50,
    rating: 4.8,
    reviewCount: 124,
    orderCount: 1240,
    approvalStatus: 'APPROVED',
    createdAt: '2024-10-01T08:00:00.000Z',
    deliveryType: 'NATIONAL',
    platformModes: ['ORGANIC', 'RYTHU_BAZAR'],
    productZones: [{ productId: 'p1', zoneId: 'zone-ts', isAvailable: true, priceOverride: null }],
  },
  {
    id: 'p2',
    name: 'Cold-Press Coconut Oil',
    slug: 'cold-press-coconut-oil',
    description: 'Pure, wood-pressed coconut oil from sun-dried coconuts of Nizamabad. Rich in MCTs and natural aroma.',
    shortDesc: 'Traditional wood-pressed extra virgin oil.',
    price: 32000,
    originalPrice: 42000,
    images: ['https://images.unsplash.com/photo-1590779033100-9f60705a2f3b?w=900&auto=format&fit=crop'],
    categoryId: 'oils',
    category: categories[1],
    region: 'Nizamabad',
    weight: ['500 ml', '1 L'],
    certifications: ['NPOP'],
    tags: ['Premium', 'Cold-Pressed'],
    healthGoalTags: ['heart-health', 'skin'],
    seasonalMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    nutritionFacts: { servingSize: '15ml', calories: 120, protein: '0g', carbs: '0g', fat: '14g', fiber: '0g', sugar: '0g', sodium: '0mg' },
    isFeatured: true,
    isOrganic: true,
    inStock: true,
    stock: 200,
    lowStockThresh: 20,
    rating: 4.9,
    reviewCount: 89,
    orderCount: 890,
    approvalStatus: 'APPROVED',
    createdAt: '2024-11-01T08:00:00.000Z',
    deliveryType: 'NATIONAL',
    platformModes: ['ORGANIC', 'RYTHU_BAZAR'],
    productZones: [{ productId: 'p2', zoneId: 'zone-ts', isAvailable: true, priceOverride: null }],
  },
  {
    id: 'p3',
    name: 'A2 Cow Ghee',
    slug: 'a2-cow-ghee',
    description: 'Golden A2 ghee made from the milk of grass-fed Gir cows in Sangareddy using the traditional bilona method.',
    shortDesc: 'Traditional Bilona-churned Gir cow ghee.',
    price: 68000,
    originalPrice: 85000,
    images: ['https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=900&auto=format&fit=crop'],
    categoryId: 'dairy',
    category: categories[5],
    region: 'Sangareddy',
    weight: ['500 ml', '1 L'],
    certifications: ['NPOP'],
    tags: ['A2 Premium', 'Bilona'],
    healthGoalTags: ['immunity', 'digestion'],
    seasonalMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    nutritionFacts: { servingSize: '15g', calories: 135, protein: '0g', carbs: '0g', fat: '15g', fiber: '0g', sugar: '0g', sodium: '0mg' },
    isFeatured: true,
    isOrganic: true,
    inStock: true,
    stock: 150,
    lowStockThresh: 15,
    rating: 5.0,
    reviewCount: 312,
    orderCount: 3120,
    approvalStatus: 'APPROVED',
    createdAt: '2024-11-15T08:00:00.000Z',
    deliveryType: 'NATIONAL',
    platformModes: ['ORGANIC', 'RYTHU_BAZAR'],
    productZones: [{ productId: 'p3', zoneId: 'zone-ts', isAvailable: true, priceOverride: null }],
  },
  {
    id: 'p4',
    name: 'Turmeric Powder',
    slug: 'turmeric-powder',
    description: 'High-curcumin turmeric powder from Medak, processed without any chemical additives.',
    shortDesc: 'Pure, stone-ground medicinal turmeric.',
    price: 9500,
    originalPrice: 13000,
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=900&auto=format&fit=crop'],
    categoryId: 'spices',
    category: categories[2],
    region: 'Medak',
    weight: ['200 g', '500 g'],
    certifications: ['NPOP'],
    tags: ['Pure', 'Medicinal'],
    healthGoalTags: ['immunity', 'anti-inflammatory'],
    seasonalMonths: [9, 10, 11, 12],
    nutritionFacts: { servingSize: '5g', calories: 15, protein: '0.4g', carbs: '3g', fat: '0.2g', fiber: '0.5g', sugar: '0.1g', sodium: '1mg' },
    isFeatured: false,
    isOrganic: true,
    inStock: true,
    stock: 300,
    lowStockThresh: 30,
    rating: 4.7,
    reviewCount: 201,
    orderCount: 2010,
    approvalStatus: 'APPROVED',
    createdAt: '2024-09-01T08:00:00.000Z',
    deliveryType: 'NATIONAL',
    platformModes: ['ORGANIC'],
    productZones: [{ productId: 'p4', zoneId: 'zone-ts', isAvailable: true, priceOverride: null }],
  },
  {
    id: 'p5',
    name: 'Moringa Leaf Powder',
    slug: 'moringa-leaf-powder',
    description: 'Nutrient-dense superfood made from fresh Moringa leaves of Khammam, dried under shade.',
    shortDesc: 'Organic green multi-vitamin superfood.',
    price: 22000,
    originalPrice: 30000,
    images: ['https://images.unsplash.com/photo-1546749437-2114fed30e3e?w=900&auto=format&fit=crop'],
    categoryId: 'superfoods',
    category: categories[4],
    region: 'Khammam',
    weight: ['100 g', '200 g'],
    certifications: ['NPOP'],
    tags: ['Superfood', 'Detox'],
    healthGoalTags: ['energy', 'immunity'],
    seasonalMonths: [11, 12, 1, 2, 3],
    nutritionFacts: { servingSize: '10g', calories: 20, protein: '2g', carbs: '3g', fat: '0g', fiber: '1g', sugar: '0.5g', sodium: '5mg' },
    isFeatured: true,
    isOrganic: true,
    inStock: true,
    stock: 120,
    lowStockThresh: 12,
    rating: 4.9,
    reviewCount: 78,
    orderCount: 780,
    approvalStatus: 'APPROVED',
    createdAt: '2024-11-20T08:00:00.000Z',
    deliveryType: 'NATIONAL',
    platformModes: ['ORGANIC', 'ECO'],
    productZones: [{ productId: 'p5', zoneId: 'zone-ts', isAvailable: true, priceOverride: null }],
  },
  {
    id: 'p6',
    name: 'Millets Mix (5-grain)',
    slug: 'millets-mix-5-grain',
    description: 'Ancestral 5-grain millet mix from Tribal Grains of Adilabad. High fiber and low glycemic index.',
    shortDesc: 'Traditional tribal 5-grain millet blend.',
    price: 16500,
    originalPrice: 21000,
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=900&auto=format&fit=crop'],
    categoryId: 'grains',
    category: categories[0],
    region: 'Adilabad',
    weight: ['1 kg', '2 kg'],
    certifications: ['NPOP'],
    tags: ['Tribal', 'Ancient Grain'],
    healthGoalTags: ['weightloss', 'energy'],
    seasonalMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    nutritionFacts: { servingSize: '100g', calories: 350, protein: '11g', carbs: '65g', fat: '3g', fiber: '9g', sugar: '0g', sodium: '2mg' },
    isFeatured: true,
    isOrganic: true,
    inStock: true,
    stock: 250,
    lowStockThresh: 25,
    rating: 4.6,
    reviewCount: 142,
    orderCount: 1420,
    approvalStatus: 'APPROVED',
    createdAt: '2024-10-10T08:00:00.000Z',
    deliveryType: 'NATIONAL',
    platformModes: ['ORGANIC'],
    productZones: [{ productId: 'p6', zoneId: 'zone-ts', isAvailable: true, priceOverride: null }],
  },
  {
    id: 'p7',
    name: 'Red Lentils (Masoor Dal)',
    slug: 'red-lentils-masoor-dal',
    description: 'Unpolished red lentils from Sunita Farms, Adilabad. Protein-rich and easy to digest.',
    shortDesc: 'Premium unpolished organic red lentils.',
    price: 14500,
    originalPrice: 19500,
    images: ['https://images.unsplash.com/photo-1515942400420-2b98fed1f515?w=900&auto=format&fit=crop'],
    categoryId: 'pulses',
    category: categories[3],
    region: 'Adilabad',
    weight: ['1 kg', '2 kg'],
    certifications: ['NPOP'],
    tags: ['Protein Rich', 'Unpolished'],
    healthGoalTags: ['muscle-gain', 'digestion'],
    seasonalMonths: [1, 2, 3, 4, 11, 12],
    nutritionFacts: { servingSize: '100g', calories: 350, protein: '24g', carbs: '60g', fat: '1g', fiber: '10g', sugar: '2g', sodium: '5mg' },
    isFeatured: false,
    isOrganic: true,
    inStock: true,
    stock: 400,
    lowStockThresh: 40,
    rating: 4.8,
    reviewCount: 96,
    orderCount: 960,
    approvalStatus: 'APPROVED',
    createdAt: '2024-11-05T08:00:00.000Z',
    deliveryType: 'NATIONAL',
    platformModes: ['ORGANIC', 'RYTHU_BAZAR'],
    productZones: [{ productId: 'p7', zoneId: 'zone-ts', isAvailable: true, priceOverride: null }],
  },
  {
    id: 'p8',
    name: 'Raw Wildflower Honey',
    slug: 'raw-wildflower-honey',
    description: 'Unfiltered, raw honey collected from the wildflower forests of Bhupalpally by BeeCraft.',
    shortDesc: 'Aromatic raw forest wildflower honey.',
    price: 45000,
    originalPrice: 58000,
    images: ['https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=900&auto=format&fit=crop'],
    categoryId: 'sweeteners',
    category: categories[6],
    region: 'Bhupalpally',
    weight: ['250 g', '500 g'],
    certifications: ['NPOP'],
    tags: ['Pure', 'Raw'],
    healthGoalTags: ['immunity', 'energy'],
    seasonalMonths: [3, 4, 5, 6, 11, 12],
    nutritionFacts: { servingSize: '20g', calories: 60, protein: '0g', carbs: '17g', fat: '0g', fiber: '0g', sugar: '16g', sodium: '0mg' },
    isFeatured: true,
    isOrganic: true,
    inStock: true,
    stock: 80,
    lowStockThresh: 8,
    rating: 4.9,
    reviewCount: 156,
    orderCount: 1560,
    approvalStatus: 'APPROVED',
    createdAt: '2024-12-01T08:00:00.000Z',
    deliveryType: 'NATIONAL',
    platformModes: ['ORGANIC'],
    productZones: [{ productId: 'p8', zoneId: 'zone-ts', isAvailable: true, priceOverride: null }],
  },
]

export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    messages: [
      { text: 'Fresh farm lots are now live for Hyderabad West.' },
      { text: 'Use code FRESH360 for 12% off on premium fruit boxes.', bold: true },
    ],
    bgColor: '#12231B',
    textColor: '#F8F4EA',
    rotateEvery: 4,
    isActive: true,
  },
]

export const mockBanners: Banner[] = [
  {
    id: 'banner-1',
    title: 'Earth-First. Premium-Only.',
    subtitle: 'NPOP Certified Organic',
    description: 'Directly from our chemical-free orchards. Pure, nutrient-dense, and delivered within 24 hours.',
    desktopImageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=2000&auto=format&fit=crop',
    mobileImageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=800&auto=format&fit=crop',
    overlayColor: 'rgba(27, 67, 50, 0.4)',
    ctaText: 'Explore Collection',
    ctaLink: '/shop',
    badgeText: 'Lush & Organic',
    displayOrder: 1,
    isActive: true,
    productId: 'p1',
    product: mockProducts[0],
  },
  {
    id: 'banner-2',
    title: 'Rythu Bazar: The Farmer Drop',
    subtitle: 'Harvesting Live Now',
    description: 'Skip the middlemen. Join live harvest batches and get the freshest price directly from the farmer.',
    desktopImageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1400&auto=format&fit=crop',
    mobileImageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&auto=format&fit=crop',
    overlayColor: 'rgba(56, 14, 14, 0.45)',
    ctaText: 'View Batches',
    ctaLink: '/shop?mode=RYTHU_BAZAR',
    badgeText: 'Direct-to-Home',
    displayOrder: 2,
    isActive: true,
    mode: 'RYTHU_BAZAR',
    productId: 'p2',
    product: mockProducts[1],
  },
  {
    id: 'banner-3',
    title: 'Purely Sustainable',
    subtitle: 'Eco-conscious Living',
    description: 'Ethically sourced, plastic-free packaging, and carbon-neutral delivery for all your home essentials.',
    desktopImageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=2000&auto=format&fit=crop',
    mobileImageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop',
    overlayColor: 'rgba(45, 80, 22, 0.4)',
    ctaText: 'Go Sustainable',
    ctaLink: '/shop?mode=SUSTAINABLE',
    badgeText: 'Eco Friendly',
    displayOrder: 3,
    isActive: true,
    mode: 'SUSTAINABLE',
    productId: 'p3',
    product: mockProducts[2],
  },
]

export const mockMarqueeItems: MarqueeItem[] = [
  { id: 'mq-1', text: 'Harvested at 5:30 AM in Warangal', displayOrder: 1, isActive: true },
  { id: 'mq-2', text: '63 minute average local dispatch', displayOrder: 2, isActive: true },
  { id: 'mq-3', text: 'Verified NPOP Organic Registry Live', displayOrder: 3, isActive: true },
  { id: 'mq-4', text: 'Rythu Bazar batches close before 8 PM', displayOrder: 4, isActive: true, mode: 'RYTHU_BAZAR' },
]

export const mockFlashSale: FlashSale = {
  id: 'flash-1',
  title: 'Golden hour savings',
  productIds: ['p1', 'p2', 'p3'],
  discountType: 'PERCENT',
  discountValue: 15,
  endsAt: '2026-03-10T18:30:00.000Z',
  isActive: true,
  showOnHome: true,
  showOnShop: true,
  products: mockProducts.slice(0, 3),
}

export const mockPopup: PromoPopup = {
  id: 'popup-1',
  title: 'Unlock your premium trial basket',
  description: 'Choose your zone and mode, and we will tailor the homepage, flash sale, and delivery promise instantly.',
  couponCode: 'WELCOME360',
  ctaText: 'Start Shopping',
  ctaLink: '/shop',
  delaySeconds: 3,
  showOnce: true,
  isActive: true,
  imageUrl: 'https://images.unsplash.com/photo-1518843875459-f738682238a6?w=900&auto=format&fit=crop',
}

export const mockHomepageSections: HomepageSection[] = [
  { sectionKey: 'hero', isVisible: true, displayOrder: 1 },
  { sectionKey: 'marquee', isVisible: true, displayOrder: 2 },
  { sectionKey: 'modes', isVisible: true, displayOrder: 3 },
  { sectionKey: 'featured_products', isVisible: true, displayOrder: 4 },
  { sectionKey: 'flash_sale', isVisible: true, displayOrder: 5 },
  { sectionKey: 'rythu_batch', isVisible: true, displayOrder: 6, mode: 'RYTHU_BAZAR' },
  { sectionKey: 'testimonials', isVisible: true, displayOrder: 7 },
  { sectionKey: 'impact_numbers', isVisible: true, displayOrder: 8 },
  { sectionKey: 'newsletter', isVisible: true, displayOrder: 9 },
]

export const mockTestimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Ananya Rao',
    city: 'Warangal',
    rating: 5,
    text: 'The Organic Basmati rice quality is noticesbly premium. The fragrance is incredible.',
    isActive: true,
    displayOrder: 1,
    productId: 'p1',
    product: mockProducts[0],
  },
  {
    id: 'test-2',
    name: 'Rahul Varma',
    city: 'Nizamabad',
    rating: 5,
    text: 'Direct farmer lots make buying pure coconut oil feel transparent and modern.',
    isActive: true,
    displayOrder: 2,
    mode: 'RYTHU_BAZAR',
    productId: 'p2',
    product: mockProducts[1],
  },
  {
    id: 'test-3',
    name: 'Megha Patel',
    city: 'Sangareddy',
    rating: 5,
    text: 'Premium Gir cow ghee with high purity. The A2 verification is what I needed.',
    isActive: true,
    displayOrder: 3,
    productId: 'p3',
    product: mockProducts[2],
  },
]

export const mockModes: ZoneModeConfig[] = [
  {
    id: 'mode-1',
    zoneId: 'zone-hyd',
    mode: 'ORGANIC',
    isEnabled: true,
    isDefault: true,
    label: 'Organic',
    description: 'Certified and curated premium organic produce.',
    accentColor: '#21513A',
  },
  {
    id: 'mode-2',
    zoneId: 'zone-hyd',
    mode: 'RYTHU_BAZAR',
    isEnabled: true,
    isDefault: false,
    label: 'Rythu Bazar',
    description: 'Direct farmer lots with batch closing windows.',
    accentColor: '#A74222',
  },
]

export const mockStorefrontData: StorefrontData = {
  announcements: mockAnnouncements,
  banners: mockBanners,
  marqueeItems: mockMarqueeItems,
  flashSale: mockFlashSale,
  featuredSlots: {
    best_sellers: [mockProducts[0], mockProducts[2], mockProducts[7], mockProducts[1]],
    new_arrivals: [mockProducts[7], mockProducts[6], mockProducts[5], mockProducts[4]],
    on_sale: mockProducts.filter((item) => item.originalPrice > item.price),
    seasonal: [mockProducts[0], mockProducts[3], mockProducts[7]],
  },
  popup: mockPopup,
  sections: mockHomepageSections,
  testimonials: mockTestimonials,
  modes: mockModes,
}

export const mockRythuBatches: RythuBatch[] = [
  {
    id: 'batch-1',
    zoneId: 'zone-ts',
    productId: 'p1',
    farmerId: 'farmer-1',
    product: mockProducts[0],
    farmerName: 'Ravi Kumar',
    farmerCity: 'Warangal',
    batchQty: 500,
    availableQty: 450,
    harvestDate: '2024-10-15T05:30:00.000Z',
    closesAt: '2024-12-30T20:00:00.000Z',
    pricePerUnit: 18000,
    isActive: true,
  },
  {
    id: 'batch-2',
    zoneId: 'zone-ts',
    productId: 'p2',
    farmerId: 'farmer-2',
    product: mockProducts[1],
    farmerName: 'Priya Farms',
    farmerCity: 'Nizamabad',
    batchQty: 200,
    availableQty: 180,
    harvestDate: '2024-11-01T06:15:00.000Z',
    closesAt: '2024-12-30T19:30:00.000Z',
    pricePerUnit: 32000,
    isActive: true,
  },
]

export const mockZones: Zone[] = [
  {
    id: 'zone-ts',
    name: 'Telangana Core',
    type: 'STATE',
    isActive: true,
    deliveryFee: 4900,
    freeDeliveryThreshold: 49900,
    codAvailable: true,
    codMaxOrder: 200000,
    pincodes: [{ zoneId: 'zone-ts', pincode: '506001' }, { zoneId: 'zone-ts', pincode: '503001' }],
    modeConfigs: mockModes,
  },
]

export const mockCmsCollections = {
  zones: mockZones,
  announcements: mockAnnouncements,
  banners: mockBanners,
  flashSales: [mockFlashSale],
  homepageSections: mockHomepageSections,
  featuredSlots: [
    { id: 'slot-1', section: 'best_sellers', productId: 'p1', product: mockProducts[0], displayOrder: 1, isActive: true },
    { id: 'slot-2', section: 'new_arrivals', productId: 'p3', product: mockProducts[2], displayOrder: 2, isActive: true },
  ],
  rythuBatches: mockRythuBatches,
  testimonials: mockTestimonials,
  popups: [mockPopup],
}

export const mockAdminDashboard = {
  revenue: 6842000,
  revenueGrowth: 18.4,
  orders: 1280,
  ordersGrowth: 12.2,
  customers: 4960,
  customersGrowth: 9.5,
  products: 286,
  productsGrowth: 7.4,
  revenueHistory: [
    { date: 'Mar 01', revenue: 720000 },
    { date: 'Mar 02', revenue: 810000 },
    { date: 'Mar 03', revenue: 780000 },
    { date: 'Mar 04', revenue: 920000 },
    { date: 'Mar 05', revenue: 1050000 },
    { date: 'Mar 06', revenue: 1110000 },
    { date: 'Mar 07', revenue: 1450000 },
  ],
  orderStatuses: [
    { name: 'Delivered', value: 62 },
    { name: 'Packed', value: 18 },
    { name: 'Farmer Hold', value: 9 },
    { name: 'Issue', value: 4 },
  ],
}

export const mockVendorDashboard = {
  revenue: 452000,
  orders: 42,
  activeProducts: 15,
  avgRating: 4.8,
  revenueHistory: [
    { date: 'Mon', revenue: 42000 },
    { date: 'Tue', revenue: 61000 },
    { date: 'Wed', revenue: 59000 },
    { date: 'Thu', revenue: 72000 },
    { date: 'Fri', revenue: 81000 },
    { date: 'Sat', revenue: 69000 },
    { date: 'Sun', revenue: 68000 },
  ],
}

export const mockVendorOrders = [
  {
    id: 'ORD-1001',
    customerName: 'Riya Singh',
    totalItems: 3,
    amount: 45000,
    status: 'PENDING',
    createdAt: '2026-03-09T08:20:00.000Z',
    distanceKm: 4.2,
    cluster: 'Jubilee Hills',
  },
  {
    id: 'ORD-1002',
    customerName: 'Amit Kumar',
    totalItems: 1,
    amount: 15000,
    status: 'PROCESSING',
    createdAt: '2026-03-08T10:15:00.000Z',
    distanceKm: 7.8,
    cluster: 'Madhapur',
  },
  {
    id: 'ORD-1003',
    customerName: 'Sneha Patel',
    totalItems: 5,
    amount: 125000,
    status: 'DELIVERED',
    createdAt: '2026-03-07T14:10:00.000Z',
    distanceKm: 11.5,
    cluster: 'Kokapet',
  },
]
