import { Product } from '@next360/types'

export const MOCK_CATEGORIES = [
  { id: 'fruits', name: 'Fruits', slug: 'fruits', icon: '🍎', _count: { products: 3 } },
  { id: 'vegetables', name: 'Vegetables', slug: 'vegetables', icon: '🥦', _count: { products: 5 } },
  { id: 'dairy', name: 'Dairy & Eggs', slug: 'dairy', icon: '🥚', _count: { products: 2 } },
  { id: 'grains', name: 'Grains', slug: 'grains', icon: '🌾', _count: { products: 2 } },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Premium HASS Avocados',
    slug: 'premium-hass-avocados',
    shortDesc: 'Creamy Hass avocados, perfect for your breakfast toast.',
    description: 'Our Hass avocados are sourced from certified organic orchards. They are rich in healthy fats and fiber. Each avocado is hand-picked at peak ripeness to ensure the best quality and flavor for your kitchen.',
    price: 39900,
    originalPrice: 49900,
    images: ['https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800'],
    categoryId: 'fruits',
    category: { id: 'fruits', name: 'Fruits', slug: 'fruits', icon: '🍎' },
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    stock: 45,
    region: 'Himachal Pradesh',
    healthGoalTags: ['heart-health', 'skin'],
    seasonalMonths: [1, 2, 3, 4, 10, 11, 12],
    certifications: ['India Organic', 'USDA Organic'],
    weight: ['500g', '1kg'],
    isFeatured: true,
    orderCount: 1200,
    isOrganic: true,
    tags: ['fresh', 'organic', 'avocado'],
    approvalStatus: 'APPROVED',
    lowStockThresh: 10,
    nutritionFacts: { 
      servingSize: '100g',
      calories: 160, 
      fat: '15g', 
      sodium: '7mg', 
      carbs: '9g',
      fiber: '7g',
      sugar: '0.7g',
      protein: '2g',
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p2',
    name: 'Organic Cherry Tomatoes',
    slug: 'organic-cherry-tomatoes',
    shortDesc: 'Sweet and juicy bite-sized tomatoes.',
    description: 'Vine-ripened organic cherry tomatoes. Great for salads and snacks. These tomatoes are grown in our volcanic soil farms, giving them a unique sweetness and rich lycopene content.',
    price: 15000,
    originalPrice: 18000,
    images: ['https://images.unsplash.com/photo-1561131245-c9e7c76a593c?w=800'],
    categoryId: 'vegetables',
    category: { id: 'vegetables', name: 'Vegetables', slug: 'vegetables', icon: '🥦' },
    rating: 4.5,
    reviewCount: 89,
    inStock: true,
    stock: 120,
    region: 'Maharashtra',
    healthGoalTags: ['immunity', 'weightloss'],
    seasonalMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    certifications: ['India Organic'],
    weight: ['250g', '500g'],
    isFeatured: true,
    orderCount: 850,
    isOrganic: true,
    tags: ['fresh', 'salad', 'vegetable'],
    approvalStatus: 'APPROVED',
    lowStockThresh: 15,
    nutritionFacts: { 
      servingSize: '100g',
      calories: 18, 
      fat: '0.2g', 
      sodium: '5mg', 
      carbs: '3.9g',
      fiber: '1.2g',
      sugar: '2.6g',
      protein: '0.9g'
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p3',
    name: 'Fresh Baby Spinach',
    slug: 'fresh-baby-spinach',
    shortDesc: 'Tender baby spinach leaves, triple washed.',
    description: 'Hydroponically grown organic baby spinach. Nutrient dense and ready to eat. Perfect for green smoothies, fresh salads, or a quick sauté with garlic and olive oil.',
    price: 12000,
    originalPrice: 15000,
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f829a?w=800'],
    categoryId: 'vegetables',
    category: { id: 'vegetables', name: 'Vegetables', slug: 'vegetables', icon: '🥦' },
    rating: 4.9,
    reviewCount: 210,
    inStock: true,
    stock: 60,
    region: 'Ooty',
    healthGoalTags: ['detox', 'digestion', 'energy'],
    seasonalMonths: [1, 2, 3, 10, 11, 12],
    certifications: ['India Organic'],
    weight: ['200g', '500g'],
    isFeatured: true,
    orderCount: 1500,
    isOrganic: true,
    tags: ['greens', 'detox', 'fresh'],
    approvalStatus: 'APPROVED',
    lowStockThresh: 5,
    nutritionFacts: { 
      servingSize: '100g',
      calories: 23, 
      fat: '0.4g', 
      sodium: '79mg', 
      carbs: '3.6g',
      fiber: '2.2g',
      sugar: '0.4g',
      protein: '2.9g'
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p4',
    name: 'Organic Blueberries',
    slug: 'organic-blueberries',
    shortDesc: 'Antioxidant-rich fresh organic blueberries.',
    description: 'Plump and sweet blueberries from the Nilgiri hills. These berries are high in antioxidants and vitamins.',
    price: 45000,
    originalPrice: 55000,
    images: ['https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=800'],
    categoryId: 'fruits',
    category: { id: 'fruits', name: 'Fruits', slug: 'fruits', icon: '🍎' },
    rating: 4.7,
    reviewCount: 320,
    inStock: true,
    stock: 25,
    region: 'Nilgiris',
    healthGoalTags: ['brain-health', 'immunity'],
    seasonalMonths: [5, 6, 7, 8],
    certifications: ['India Organic'],
    weight: ['125g', '250g'],
    isFeatured: false,
    orderCount: 2000,
    isOrganic: true,
    tags: ['berries', 'superfood', 'fresh'],
    approvalStatus: 'APPROVED',
    lowStockThresh: 5,
    nutritionFacts: { 
      servingSize: '100g',
      calories: 57, 
      fat: '0.3g', 
      sodium: '1mg', 
      carbs: '14g',
      fiber: '2.4g',
      sugar: '10g',
      protein: '0.7g'
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p5',
    name: 'A2 Vedic Ghee',
    slug: 'a2-vedic-ghee',
    shortDesc: 'Traditional bilona churned A2 Gir cow ghee.',
    description: 'Our A2 Ghee is made from the milk of grass-fed Gir cows using the traditional wooden churn (Bilona) method. It is highly medicinal and nutritious.',
    price: 185000,
    originalPrice: 210000,
    images: ['https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=800'],
    categoryId: 'dairy',
    category: { id: 'dairy', name: 'Dairy & Eggs', slug: 'dairy', icon: '🥚' },
    rating: 5.0,
    reviewCount: 450,
    inStock: true,
    stock: 15,
    region: 'Gujarat',
    healthGoalTags: ['digestion', 'immunity', 'energy'],
    seasonalMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    certifications: ['India Organic', 'Jaivik Bharat'],
    weight: ['500ml', '1L'],
    isFeatured: true,
    orderCount: 3000,
    isOrganic: true,
    tags: ['ghee', 'dairy', 'superfood'],
    approvalStatus: 'APPROVED',
    lowStockThresh: 5,
    nutritionFacts: { 
      servingSize: '15g',
      calories: 135, 
      fat: '15g', 
      sodium: '0mg', 
      carbs: '0g',
      fiber: '0g',
      sugar: '0g',
      protein: '0g'
    },
    createdAt: new Date().toISOString()
  },
]

export const MOCK_REVIEWS = [
  {
    id: 'r1',
    productId: 'p1',
    userName: 'Anita Sharma',
    rating: 5,
    comment: 'The best avocados I have bought in India. So creamy and perfectly ripe!',
    date: '2 Oct 2023',
    isVerified: true,
    likes: 12
  },
  {
    id: 'r2',
    productId: 'p1',
    userName: 'Vikram Malhotra',
    rating: 4,
    comment: 'A bit expensive but the quality is top-notch. Delivery was on time.',
    date: '15 Sep 2023',
    isVerified: true,
    likes: 5
  },
  {
    id: 'r3',
    productId: 'p5',
    userName: 'Rohan Gupta',
    rating: 5,
    comment: 'Authentic taste. Reminds me of the ghee my grandmother used to make.',
    date: '28 Sep 2023',
    isVerified: true,
    likes: 24
  }
]

export const MOCK_TESTIMONIALS = [
  {
    id: 't1',
    name: 'Sarah Johnson',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    rating: 5,
    review: 'The quality of the HASS avocados is unparalleled. I finally found a place that delivers true organic goodness to my doorstep.',
    city: 'Bangalore'
  },
  {
    id: 't2',
    name: 'David Chen',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    rating: 5,
    review: 'Their A2 Ghee has changed my morning routine. The aroma and purity are just like what my mom used to get from the village.',
    city: 'Mumbai'
  },
  {
    id: 't3',
    name: 'Priyanka Das',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    rating: 4,
    review: 'Fresh, triple-washed baby spinach is a lifesaver for my busy mornings. Highly recommend the subscription!',
    city: 'Delhi'
  }
]

export const MOCK_BLOG_POSTS = [
  {
    id: 'b1',
    title: 'Top 5 Summer Superfoods for Natural Immunity',
    slug: 'summer-superfoods-immunity',
    excerpt: 'Discover the best organic produce to keep your family healthy and energized during the warmer months.',
    thumbnail: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=800',
    category: 'Nutrition',
    publishedAt: '2023-10-01T10:00:00Z'
  },
  {
    id: 'b2',
    title: 'Why A2 Gir Cow Ghee is Your Kitchen Essential',
    slug: 'a2-ghee-kitchen-essential',
    excerpt: 'The ancient wisdom of Bilona churned ghee and its modern health benefits explained by nutritional experts.',
    thumbnail: 'https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=800',
    category: 'Health',
    publishedAt: '2023-09-25T08:30:00Z'
  },
  {
    id: 'b3',
    title: 'Sustainable Farming: Direct from Local Orchards',
    slug: 'sustainable-farming-local-orchards',
    excerpt: 'A behind-the-scenes look at how Next360 partners with small-scale farmers to bring you peak freshness.',
    thumbnail: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800',
    category: 'Sustainability',
    publishedAt: '2023-09-15T14:45:00Z'
  }
]
